(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const cfg = window.LOADFLOW_CONFIG || {};
  const ready = /^https:\/\//.test(cfg.supabaseUrl || '') && cfg.supabaseAnonKey && window.supabase;
  let db, timer, clockTimer, isRefreshing=false, dashboard={docks:[],tickets:[]};
  let lastTrackingStatus=null, currentTrackingData=null;
  let adminAlertsInitialized=false, adminAlertsEnabled=localStorage.getItem('loadflow_admin_alerts')==='1', adminAudioContext=null;
  const knownWaitingIds=new Set();
  const storageKey='loadflow_tracking_token';
  const VAPID_PUBLIC_KEY='BBTmkscLo3MjwNDIl0hXR-PxOfDObQ8IUWQpZ8Sqb8EW8cMsUIWBIXFoNXwsJlx3kWznBpx-jTRKLh_dJmmCw-0';
  const views=['config','checkin','tracking','login','admin'];
  const show=name=>views.forEach(v=>$(`${v}-view`).classList.toggle('hidden',v!==name));
  const error=(id,msg)=>{const el=$(id);if(!el)return;el.textContent=msg||'';el.classList.toggle('hidden',!msg)};
  const element=(tag,cls,val)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(val!=null)el.textContent=String(val);return el};
  const button=(label,fn,kind='secondary')=>{const b=element('button',`button ${kind} compact`,label);b.type='button';b.addEventListener('click',fn);return b};
  const cleanError=e=>/failed to fetch|network|ERR_EMPTY_RESPONSE/i.test(e?.message||'')?'Falha de conexão. Tente novamente.':(e?.message||'Não foi possível concluir.');
  const clearTimers=()=>{if(timer)clearInterval(timer);if(clockTimer)clearInterval(clockTimer);timer=clockTimer=null};
  const fmtDateTime=t=>t?new Date(t).toLocaleString('pt-BR',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit',timeZone:'America/Sao_Paulo'}):'—';
  const durationMs=(start,end)=>Math.max(0,new Date(end||Date.now())-new Date(start));
  const fmtDuration=ms=>{const min=Math.floor(ms/60000),h=Math.floor(min/60),m=min%60;return h?`${h}h ${String(m).padStart(2,'0')}min`:`${m} min`};
  const fmtClock=ms=>{const s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`};
  const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
  const isStandalone=()=>window.matchMedia?.('(display-mode: standalone)').matches||navigator.standalone===true;
  function urlBase64ToUint8Array(s){const p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(b);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}

  function setupAdminAlerts(){const head=document.querySelector('.admin-head'),logout=$('logout');if(!head||!logout)return;let actions=head.querySelector('.admin-actions');if(!actions){actions=element('div','admin-actions');head.append(actions);actions.append(logout)}if(!$('admin-alert-toggle')){const b=button('Ativar alertas',activateAdminAlerts);b.id='admin-alert-toggle';actions.insertBefore(b,logout)}updateAdminAlertButton()}
  function updateAdminAlertButton(){const b=$('admin-alert-toggle');if(!b)return;b.textContent=adminAlertsEnabled?'Alertas ativos':'Ativar alertas';b.classList.toggle('alert-enabled',adminAlertsEnabled)}
  async function activateAdminAlerts(){adminAlertsEnabled=true;localStorage.setItem('loadflow_admin_alerts','1');try{const C=window.AudioContext||window.webkitAudioContext;if(C&&!adminAudioContext)adminAudioContext=new C();if(adminAudioContext?.state==='suspended')await adminAudioContext.resume()}catch{}try{if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission()}catch{}updateAdminAlertButton();showAdminToast({number:'',first_name:'LoadFlow',last_name:'',plate:'',load_number:''},true)}
  function beep(){if(!adminAlertsEnabled)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;if(!adminAudioContext)adminAudioContext=new C();if(adminAudioContext.state==='suspended')return;const c=adminAudioContext,n=c.currentTime;[[0,880],[.22,660]].forEach(([o,f])=>{const osc=c.createOscillator(),g=c.createGain();osc.frequency.value=f;g.gain.setValueAtTime(.0001,n+o);g.gain.exponentialRampToValueAtTime(.18,n+o+.02);g.gain.exponentialRampToValueAtTime(.0001,n+o+.16);osc.connect(g);g.connect(c.destination);osc.start(n+o);osc.stop(n+o+.18)})}catch{}}
  function showAdminToast(t,activation=false){const toast=element('div','admin-checkin-alert'),x=element('button','admin-alert-close','×');x.onclick=()=>toast.remove();const title=element('strong','',activation?'Alertas ativados':'Novo motorista no carregamento');const body=element('p','',activation?'Você será avisado quando houver um novo check-in.':`Load ${t.load_number} · ${t.first_name} ${t.last_name} · ${t.plate}`);toast.append(x,title,body);document.body.append(toast);requestAnimationFrame(()=>toast.classList.add('show'));setTimeout(()=>{toast.classList.remove('show');setTimeout(()=>toast.remove(),350)},activation?4500:12000)}
  function notifyAdmin(t){showAdminToast(t);beep();document.title=`NOVA LOAD — ${t.load_number} | LoadFlow`;if(adminAlertsEnabled&&'Notification'in window&&Notification.permission==='granted'){try{new Notification('Novo check-in de carregamento',{body:`Load ${t.load_number} · ${t.first_name} ${t.last_name} · ${t.plate}`,tag:`loadflow-${t.id}`})}catch{}}setTimeout(()=>document.title='Painel de carregamento | LoadFlow',8000)}
  function detectNew(data){const waiting=(data?.tickets||[]).filter(t=>t.status==='waiting');if(!adminAlertsInitialized){waiting.forEach(t=>knownWaitingIds.add(t.id));adminAlertsInitialized=true;return}const fresh=waiting.filter(t=>!knownWaitingIds.has(t.id));waiting.forEach(t=>knownWaitingIds.add(t.id));fresh.forEach(notifyAdmin)}

  async function registerWorker(){if(!('serviceWorker'in navigator))return null;return navigator.serviceWorker.register('./service-worker.js',{scope:'./'})}
  function updatePushUI(state,msg){const box=$('push-box'),btn=$('push-enable'),help=$('push-help');if(!box||!btn||!help)return;box.classList.remove('push-on','push-warning');if(state==='on'){box.classList.add('push-on');btn.textContent='Avisos de chamada ativados';btn.disabled=true;help.textContent=msg||'Você receberá uma notificação quando uma doca for liberada.'}else if(state==='ios'){box.classList.add('push-warning');btn.textContent='Como ativar no iPhone';btn.disabled=false;help.textContent='No iPhone, adicione o LoadFlow à Tela de Início, abra pelo ícone e tente novamente.'}else if(state==='denied'){box.classList.add('push-warning');btn.textContent='Notificações bloqueadas';btn.disabled=true;help.textContent='Libere notificações nas configurações do navegador.'}else{btn.textContent='Ativar aviso mesmo com o site minimizado';btn.disabled=false;help.textContent=msg||'Ative para receber a chamada no celular.'}}
  async function saveSubscription(token,sub){const j=sub.toJSON(),k=j.keys||{};if(!j.endpoint||!k.p256dh||!k.auth)throw new Error('Assinatura de notificação incompleta.');const {error:e}=await db.rpc('loading_driver_save_push_subscription',{p_token:token,p_endpoint:j.endpoint,p_p256dh:k.p256dh,p_auth:k.auth});if(e)throw e}
  async function syncPush(token){if(isIOS()&&!isStandalone()){updatePushUI('ios');return}if(!('Notification'in window)||!('PushManager'in window)||!('serviceWorker'in navigator)){updatePushUI('off','Notificações push não disponíveis neste navegador.');return}if(Notification.permission==='denied'){updatePushUI('denied');return}try{const reg=await registerWorker(),sub=await reg?.pushManager.getSubscription();if(sub&&Notification.permission==='granted'){await saveSubscription(token,sub);updatePushUI('on')}else updatePushUI('off')}catch{updatePushUI('off')}}
  async function enablePush(){const token=new URLSearchParams(location.search).get('ticket')||localStorage.getItem(storageKey);if(!token)return;if(isIOS()&&!isStandalone()){updatePushUI('ios');return}try{const reg=await registerWorker(),perm=await Notification.requestPermission();if(perm!=='granted'){updatePushUI(perm==='denied'?'denied':'off');return}let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(VAPID_PUBLIC_KEY)});await saveSubscription(token,sub);updatePushUI('on');try{reg.showNotification('LoadFlow',{body:'Avisos ativados. Você será notificado quando for chamado.',icon:'./icon-192.png',tag:'loadflow-enabled'})}catch{}}catch(e){updatePushUI('off',cleanError(e))}}

  function setTrackingAppearance(status,dock){const v=$('tracking-view');v.classList.toggle('called-screen',status==='called');if(status==='called'){$('ticket-status').textContent='VOCÊ FOI CHAMADO';$('ticket-status').className='pill active call-pill';$('ticket-message').textContent=`DIRIJA-SE À ${String(dock||'DOCA INDICADA').toUpperCase()}`;document.title=`CHAMADO — ${dock} | LoadFlow`}else if(status==='done'){$('ticket-status').textContent='CARREGAMENTO CONCLUÍDO';$('ticket-status').className='pill done';$('ticket-message').textContent='Seu carregamento foi finalizado. Obrigado!';document.title='Carregamento concluído | LoadFlow'}else if(status==='cancelled'){$('ticket-status').textContent='CHECK-IN CANCELADO';$('ticket-status').className='pill done';$('ticket-message').textContent='Seu check-in foi cancelado.'}else{$('ticket-status').textContent='AGUARDANDO';$('ticket-status').className='pill';$('ticket-message').textContent='Você está na fila de carregamento.'}}
  function routeTracking(token){localStorage.setItem(storageKey,token);history.replaceState(null,'',`?ticket=${encodeURIComponent(token)}`);show('tracking');clearTimers();lastTrackingStatus=null;refreshTracking(token);syncPush(token);clockTimer=setInterval(()=>{if(currentTrackingData)$('ticket-dwell').textContent=fmtClock(durationMs(currentTrackingData.created_at,currentTrackingData.finished_at))},1000);timer=setInterval(()=>refreshTracking(token),8000)}
  async function refreshTracking(token){const {data,error:e}=await db.rpc('loading_driver_status',{p_token:token});if(e){error('tracking-error',cleanError(e));return}if(!data){error('tracking-error','Senha não encontrada.');return}currentTrackingData=data;error('tracking-error',null);$('ticket-number').textContent=String(data.number).padStart(4,'0');$('ticket-load').textContent=data.load_number;$('ticket-plate').textContent=data.plate;$('ticket-position').textContent=data.position||'—';$('ticket-dock').textContent=data.dock||'—';$('ticket-dwell').textContent=fmtClock(durationMs(data.created_at,data.finished_at));if(data.status==='called'&&lastTrackingStatus!=='called'&&navigator.vibrate)try{navigator.vibrate([500,180,500,180,900])}catch{}setTrackingAppearance(data.status,data.dock);lastTrackingStatus=data.status;if(['done','cancelled'].includes(data.status)){localStorage.removeItem(storageKey);if(timer)clearInterval(timer);timer=null}}
  async function checkIn(ev){ev.preventDefault();error('checkin-error','');const first=$('first-name').value.trim(),last=$('last-name').value.trim(),plate=$('plate').value.toUpperCase().replace(/[^A-Z0-9]/g,''),load=$('load-number').value.trim().toUpperCase();if(!first||!last||!/^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$/.test(plate)||!/^[A-Z0-9._\/-]{2,40}$/.test(load)){error('checkin-error','Preencha nome, sobrenome, placa e número da Load corretamente.');return}const btn=$('checkin-submit');btn.disabled=true;btn.textContent='Registrando...';const {data,error:e}=await db.rpc('loading_driver_checkin',{p_first_name:first,p_last_name:last,p_plate:plate,p_load_number:load});btn.disabled=false;btn.textContent='Entrar na fila de carregamento';if(e){error('checkin-error',cleanError(e));return}routeTracking(data.tracking_token)}
  async function login(ev){ev.preventDefault();error('login-error','');const {error:e}=await db.auth.signInWithPassword({email:$('login-email').value.trim(),password:$('login-password').value});if(e){error('login-error','Credenciais incorretas.');return}const {data,error:a}=await db.rpc('is_dock_admin');if(a||!data){await db.auth.signOut();error('login-error','Este usuário não tem permissão administrativa.');return}openAdmin()}

  async function callNext(dockId){error('admin-error',null);const {data,error:e}=await db.rpc('loading_admin_call_next',{p_dock_id:dockId});if(e){error('admin-error',cleanError(e));return}try{await db.functions.invoke('notify-loading-driver',{body:{ticket_id:data.ticket_id,dock:data.dock,app_url:`${location.origin}${location.pathname}`}})}catch{}await refreshAdmin()}
  async function action(name,params){const {error:e}=await db.rpc(name,params);if(e){error('admin-error',cleanError(e));return}await refreshAdmin()}
  async function refreshAdmin(){if(isRefreshing)return;isRefreshing=true;try{const {data,error:e}=await db.rpc('loading_admin_dashboard');if(e)throw e;detectNew(data);dashboard=data;renderAdmin();$('last-update').textContent=`Última atualização: ${new Date().toLocaleTimeString('pt-BR')}`;error('admin-error',null)}catch(e){error('admin-error',cleanError(e))}finally{isRefreshing=false}}
  function renderAdmin(){const tickets=dashboard.tickets||[],docks=dashboard.docks||[];const waiting=tickets.filter(t=>t.status==='waiting').sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)||a.number-b.number),active=tickets.filter(t=>t.status==='called'),done=tickets.filter(t=>t.status==='done'&&new Date(t.finished_at).toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'})===new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}));$('count-waiting').textContent=waiting.length;$('count-active').textContent=active.length;$('count-done').textContent=done.length;const avg=done.length?done.reduce((s,t)=>s+durationMs(t.created_at,t.finished_at),0)/done.length:0;$('avg-dwell').textContent=done.length?fmtDuration(avg):'—';$('dock-list').replaceChildren();docks.forEach(d=>{const cur=active.find(t=>t.dock_id===d.id),block=element('article',`dock ${cur?'busy':''}`),head=element('div','dock-title');head.append(element('span','',d.name),element('span','',cur?'Ocupada':'Livre'));block.append(head);if(cur){block.append(element('p','load-tag',`Load ${cur.load_number}`),element('p','',`${cur.plate} · ${cur.first_name} ${cur.last_name}`),element('p','',`Permanência: ${fmtDuration(durationMs(cur.created_at))}`),button('Finalizar carregamento',()=>action('loading_admin_finish',{p_ticket_id:cur.id}),'primary'))}else{block.append(element('p','', 'Pronta para receber o próximo motorista'),button('Chamar próximo',()=>callNext(d.id),'primary'))}$('dock-list').append(block)});
    const renderRows=(id,items,kind)=>{const p=$(id);p.replaceChildren();if(!items.length){p.append(element('div','empty',kind==='waiting'?'Nenhum motorista aguardando.':kind==='active'?'Nenhum carregamento em andamento.':'Nenhum carregamento finalizado hoje.'));return}items.forEach((t,i)=>{const row=element('article','queue-item'),detail=element('div');detail.append(element('strong','',`${kind==='waiting'?`${i+1}º · `:''}Senha ${String(t.number).padStart(4,'0')} · Load ${t.load_number} · ${t.first_name} ${t.last_name}`));const dock=docks.find(d=>d.id===t.dock_id),meta=element('div','queue-meta');meta.append(element('span','tag',t.plate),element('span','tag',`Chegada ${fmtDateTime(t.created_at)}`));if(dock)meta.append(element('span','tag',dock.name));if(kind==='history'){meta.append(element('span','tag',`Saída ${fmtDateTime(t.finished_at)}`),element('span','tag time',`Permanência ${fmtDuration(durationMs(t.created_at,t.finished_at))}`))}else meta.append(element('span','tag time',`Permanência ${fmtDuration(durationMs(t.created_at))}`));detail.append(meta);row.append(detail);if(kind!=='history')row.append(button(kind==='waiting'?'Cancelar check-in':'Cancelar carregamento',()=>{if(confirm('Deseja cancelar este registro?'))action('loading_admin_cancel',{p_ticket_id:t.id})}));p.append(row)})};renderRows('queue-list',waiting,'waiting');renderRows('active-list',active,'active');renderRows('history-list',done,'history')}
  function makeQR(){const u=new URL(location.href);u.search='';u.hash='';$('qr-url').textContent=u.href;if(window.QRCode){$('qrcode').replaceChildren();new QRCode($('qrcode'),{text:u.href,width:220,height:220,correctLevel:QRCode.CorrectLevel.M})}}
  function openAdmin(){history.replaceState(null,'','?admin=1');show('admin');clearTimers();setupAdminAlerts();makeQR();refreshAdmin();timer=setInterval(refreshAdmin,5000);clockTimer=setInterval(()=>{if(!isRefreshing&&dashboard.tickets?.length)renderAdmin()},30000)}
  async function boot(){if(!ready){show('config');return}db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:false}});registerWorker().catch(()=>{});$('checkin-form').addEventListener('submit',checkIn);$('plate').addEventListener('input',e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,7));$('load-number').addEventListener('input',e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9._\/-]/g,'').slice(0,40));$('push-enable').addEventListener('click',enablePush);$('tracking-refresh').addEventListener('click',()=>{const t=new URLSearchParams(location.search).get('ticket')||localStorage.getItem(storageKey);if(t)refreshTracking(t)});$('resume-link').addEventListener('click',e=>{e.preventDefault();const t=localStorage.getItem(storageKey);if(t)routeTracking(t);else error('checkin-error','Não encontramos uma senha salva neste celular.')});$('login-form').addEventListener('submit',login);$('admin-refresh').addEventListener('click',refreshAdmin);$('logout').addEventListener('click',async()=>{clearTimers();adminAlertsInitialized=false;knownWaitingIds.clear();await db.auth.signOut();history.replaceState(null,'','?admin=1');show('login')});$('print-qr').addEventListener('click',()=>window.print());const params=new URLSearchParams(location.search),token=params.get('ticket');if(params.has('admin')){const {data:{session}}=await db.auth.getSession();if(session){const {data}=await db.rpc('is_dock_admin');if(data){openAdmin();return}await db.auth.signOut()}show('login');return}if(token&&/^[0-9a-f-]{36}$/i.test(token)){routeTracking(token);return}if(location.hash==='#acompanhar'&&localStorage.getItem(storageKey)){routeTracking(localStorage.getItem(storageKey));return}show('checkin')}
  boot().catch(e=>{show('config');document.querySelector('#config-view p').textContent=cleanError(e)});
})();
